name: weather-analysis-and-forecasting-env
channels:
  - conda-forge
dependencies:
  - python=3.12
  - sqlite>=3.41
  - numpy
  - pandas
  - matplotlib
  - cartopy
  - metpy
  - scipy>=1.9
  - requests
  - notebook
  - ipykernel
  - herbie-data
  - xarray
  - cfgrib
  - eccodes
  - netcdf4